name: 'tekartik_pdf_js'
version: 1.0.0
description: Pdf js for the web
publish_to: none
environment:
  sdk: ^3.5.0
dependencies:
  path: any
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
      ref: dart3a
dev_dependencies:
  test: any
  build_web_compilers:
  build_runner:
